name: Email Step Workflow

on:
  workflow_dispatch:  # Allows manual run

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: 23f3001780@ds.study.iitm.ac.in
        run: echo "Hello from GitHub Actions!"
